# Site settings
title: OSSEC - Open Source SECurity
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  OSSEC is an Open Source Host-based Intrusion Detection System that performs 
  log analysis, file integrity checking, policy monitoring, rootkit detection, 
  real-time alerting and active response.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ossec.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  ossec

# Build settings
markdown: kramdown
